### ISSUE TITLE
个人中心访问存在问题

### ISSUE THREAD

**Issue by SEALiu** [jobwebs/jobs-web1#25]
**(2/2) QueryException**

SQLSTATE[42S22]: Column not found: 1054 **Unknown column 'jobs_intetion.uid'** in 'on clause' (SQL: select `sex`, `work_nature`, `occupation`, `industry`, `region`, `salary` from `jobs_personinfo` inner join `jobs_intention` on `jobs_personinfo`.`uid` = `jobs_intetion`.`uid` where `jobs_intention`.`uid` = 19)

**Comment by SEALiu** [comment]
@BadBoyLikeIT

**Comment by BadBoyLikeIT** [comment]
已经解决
