### ISSUE TITLE
投递简历成功后，自动发送站内信存在问题

### ISSUE THREAD

**Issue by SEALiu** [jobwebs/jobs-web1#40]
- 问题一：
投递简历成功后，自动给企业发送一封站内信。这时使用的是企业id `eid`，但是message模块中的`from_id`和`to_id`表示的是用户id，即`uid`。
这会导致在消息详情页面 messageDetail 查看消息详情时，无法查到 `eid` 对应的用户名，或者查到的用户名是错误的。

- 问题二：
企业查看投递记录的详情页面 deliverDetail，时会自动给响应的用户发送站内信，但是没有判断是否已经发过。导致用户会收到多条站内信。
另外，详情页面 deliverDetail 需要判断当前访问的人是不是该投递记录对应的企业，如果不是不能返回视图，而是重定向到之前的页面。

**Comment by SEALiu** [comment]
@JKJUN527

**Comment by JKJUN527** [comment]
已解决
