### ISSUE TITLE
存在的问题

### ISSUE THREAD

**Issue by SEALiu** [jobwebs/jobs-web1#48]
- 投递简历时，向backup表中插入数据时，education1，2，3如果没有就填入`null`，不要写入“未填写xxx”这类的字符串。其他字段（`industry`, `place`, `nature`等）也同理。
- 新闻评论列表，企业用户的评论无法显示。
- `jobs_enprinfo` 表中公司地址字段varchar(100)太短了，可能会不够。
@JKJUN527 @BadBoyLikeIT

**Comment by JKJUN527** [comment]
已解决
